name: Build and Publish
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node: [10, 12]
    name: ${{ matrix.os }} and node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        run: cd client
      - name: Install dependencies
        run: npm ci
      - name: Build Web client
        run: npm run build
